version: '3'

services:
  # Define a Telegraf service
  telegraf:
    image: telegraf:latest
    network_mode: bridge
    volumes:
      - ./telegraf/etc/telegraf:/etc/telegraf
    user: root
    ports:
      - "20092:8092/udp"
      - "20094:8094"
      - "20125:8125/udp"
  # Define an InfluxDB service
  influxdb:
    image: quay.io/influxdb/influx:nightly
    network_mode: bridge
    volumes:
      - ./influxdb/root/.influxdbv2:/root/.influxdbv2
    user: root
    ports:
      - "20086:8086"
  grafana:
    image: grafana/grafana:latest
    network_mode: bridge
    ports:
      - "20300:3000"
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - ./grafana/var/lib/grafana:/var/lib/grafana
      - ./grafana/etc/grafana:/etc/grafana
    user: root
